# Create the final image
FROM python:alpine
WORKDIR /scripts

# Get all the packages we need
RUN pip install libconf python-dotenv

# Copy the converter script
COPY ./scripts/env2conf.py .

# Keep the container alive
CMD ["sleep", "infinity"]

# Container is healthy if it successfully converted the env variables to OGN configuration
RUN mkdir /shared_data
HEALTHCHECK --interval=5s --timeout=1s CMD python env2conf.py > /shared_data/rtlsdr-ogn.conf

VOLUME /shared_data