# Create the final image
FROM python:alpine
WORKDIR /scripts

# Get all the tools we need
RUN apk update && \
    apk add socat

# Copy the filter scripts
COPY ./scripts/incoming.py .
COPY ./scripts/outgoing.py .

ENTRYPOINT ["socat"]
CMD ["TCP:aprs.glidernet.org:14580", "SYSTEM:'python incoming.py | socat TCP-LISTEN:14580,fork,reuseaddr - | python outgoing.py'"]

EXPOSE 14580
