# Create the final image
FROM python:alpine
WORKDIR /scripts

# Get all the packages we need
RUN pip install libconf python-dotenv

# Copy the converter script
COPY ./scripts/env2conf.py .
RUN mkdir /shared_data

# Convert the env variables to OGN configuration
CMD ["sh", "-c", "python /scripts/env2conf.py > /shared_data/rtlsdr-ogn.conf && echo 'Successfully generated OGN configuration file in /shared_data/rtlsdr-ogn.conf' && sleep infinity"]

VOLUME /shared_data
